### ISSUE TITLE
Is there anyway to make the game files save on the usb itself?

### ISSUE THREAD

**Issue by CocaColaCan36** [sahlaysta/PortableTerraria#1]
Hello, I used the tool and it works pretty well, but it only saves files to the Appdata/Local folder. I was wondering if it was possible to set up the installation folder onto the USB directly? Whenever I set up the portable creater it asked where my terraria folder was, and it was on the USB itself. So when it created the exe to actually load up terraria I'd hit play and it would say Terraria isnt installed and would create files onto the Appdata folder on the local computer.

**Comment by sahlaysta** [comment]
The created exe is meant to be placed on the USB not the other way around. (I may misunderstand your question)

**Comment by sahlaysta** [comment]
Alright this problem is being solved in an upcoming version

**Comment by sahlaysta** [comment]
New version is released. Can now change the install path.
